add_executable(shift_runtime_fun_00770e80_motion_read_runtime_state_check
  ${CMAKE_CURRENT_SOURCE_DIR}/tests/fun_00770e80_motion_read_runtime_state_check.cpp)
target_include_directories(shift_runtime_fun_00770e80_motion_read_runtime_state_check PRIVATE
  ${CMAKE_CURRENT_SOURCE_DIR}/src
  ${CMAKE_CURRENT_SOURCE_DIR}/tests)
target_link_libraries(shift_runtime_fun_00770e80_motion_read_runtime_state_check PRIVATE
  shift_runtime_physics)
target_compile_options(shift_runtime_fun_00770e80_motion_read_runtime_state_check PRIVATE
  -Wall -Wextra -Wpedantic)

if(BUILD_TESTING)
  add_test(
    NAME shift_runtime_fun_00770e80_motion_read_runtime_state
    COMMAND shift_runtime_fun_00770e80_motion_read_runtime_state_check)
endif()
